services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9200/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - course-search-net

  app:
    build: .
    container_name: coursesearch-app
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    ports:
      - '8080:8080'
    restart: on-failure
    networks:
      - course-search-net

networks:
  course-search-net:
    driver: bridge

volumes:
  es-data:
    driver: local
